/// <reference lib="webworker" />

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst } from 'workbox-strategies';

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cleanup old caches
cleanupOutdatedCaches();

// Cache Supabase API calls
registerRoute(
    ({ url }) => url.host.includes('supabase.co'),
    new NetworkFirst({
        cacheName: 'supabase-cache',
    })
);

// Gérer la réception d'une notification push
self.addEventListener('push', (event) => {
    if (!event.data) return;

    try {
        const data = event.data.json();
        const options = {
            body: data.body,
            icon: data.icon || '/crm-android-chrome-512x512_(1).png',
            badge: data.badge || '/crm-android-chrome-512x512_(1).png',
            tag: data.tag,
            data: data.data,
            vibrate: [100, 50, 100],
            actions: data.actions || []
        };

        event.waitUntil(
            self.registration.showNotification(data.title, options)
        );
    } catch (err) {
        console.error('Erreur lors de la réception du push:', err);
    }
});

// Gérer le clic sur la notification → ouvrir l'app
self.addEventListener('notificationclick', (event: any) => {
    event.notification.close();
    const url = event.notification.data?.url || '/';

    event.waitUntil(
        self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
            for (const client of clientList) {
                if (client.url.includes(self.location.origin) && 'focus' in client) {
                    client.focus();
                    if ('navigate' in client) {
                        return client.navigate(url);
                    }
                }
            }
            if (self.clients.openWindow) {
                return self.clients.openWindow(url);
            }
        })
    );
});

// Message pour forcer la mise à jour du SW
self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});
