/// <reference lib="webworker" />

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst } from 'workbox-strategies';

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cleanup old caches
cleanupOutdatedCaches();

// Cache Supabase API calls
registerRoute(
    ({ url }) => url.host.includes('supabase.co'),
    new NetworkFirst({
        cacheName: 'supabase-cache',
    })
);

// Installation immédiate — ne pas attendre que les anciens onglets se ferment
self.addEventListener('install', () => {
    self.skipWaiting();
});

// Prise de contrôle immédiate de tous les clients
self.addEventListener('activate', (event) => {
    event.waitUntil(self.clients.claim());
});

// Gérer la réception d'une notification push
self.addEventListener('push', (event) => {
    let data = {
        title: 'CRM Bruneau',
        body: '',
        icon: '/crm-android-chrome-512x512_(1).png',
        badge: '/crm-android-chrome-512x512_(1).png',
        tag: 'crm-default',
        data: { url: '/' }
    };

    try {
        if (event.data) {
            const json = event.data.json();
            data = { ...data, ...json };
        }
    } catch (e) {
        // Fallback si le payload n'est pas du JSON
        data.body = event.data?.text() || 'Nouvelle notification CRM';
    }

    event.waitUntil(
        self.registration.showNotification(data.title, {
            body: data.body,
            icon: data.icon || '/crm-android-chrome-512x512_(1).png',
            badge: data.badge || '/crm-android-chrome-512x512_(1).png',
            tag: data.tag || 'crm-default',
            requireInteraction: true,   // IMPORTANT : reste affiché jusqu'au clic
            renotify: true,             // Vibrer même si même tag
            vibrate: [200, 100, 200],
            data: data.data || { url: '/' }
        })
    );
});

// Gérer le clic sur la notification → ouvrir l'app
self.addEventListener('notificationclick', (event) => {
    event.notification.close();
    const url = event.notification.data?.url || '/';

    event.waitUntil(
        self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
            for (const client of clients) {
                if (client.url.includes(self.location.origin)) {
                    client.focus();
                    client.navigate(url);
                    return;
                }
            }
            return self.clients.openWindow(url);
        })
    );
});

// Message pour forcer la mise à jour du SW (compatibilité avec injectManifest)
self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});
